server:
  shutdown: graceful
  forward-headers-strategy: native

spring:
  application:
    name: application
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  profiles:
    include: secret
  lifecycle:
    # WAS 종료 대기 시간 15초로 설정
    timeout-per-shutdown-phase: 15s
  servlet:
    # multipart 요청 최대 크기 설정
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
